//for user login
export const AUTH_START = "AUTH_START";
export const AUTH_START_SUCCESS = "AUTH_START_SUCCESS";
export const AUTH_START_FAIL = "AUTH_START_FAIL";
export const AUTH_LOGOUT = "AUTH_LOGOUT";
export const AUTH_LOADING = "AUTH_LOADING";

//for movies
export const FETCH_MOVIES = "FETCH_MOVIES";
export const FETCH_MOVIES_START = "FETCH_MOVIES_START";
export const FETCH_MOVIES_SUCESS = "FETCH_MOVIES_SUCESS";
export const FETCH_MOVIES_FAIL = "FETCH_MOVIES_FAIL";
export const FETCH_MOVIES_LOADING = "FETCH_MOVIES_LOADING";

//for watchlist
export const FETCH_WATCHLIST = "FETCH_WATCHLIST";
export const FETCH_WATCHLIST_START = "FETCH_WATCHLIST_START";
export const FETCH_WATCHLIST_SUCESS = "FETCH_WATCHLIST_SUCESS";
export const FETCH_WATCHLIST_FAIL = "FETCH_WATCHLIST_FAIL";
export const FETCH_WATCHLIST_LOADING = "FETCH_WATCHLIST_LOADING";
export const ADD_WATCHLIST_MOVIE = "ADD_WATCHLIST_MOVIE";
